# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
windowrule = match:class .*, no_blur off
# windowrule = match:class ^(?!(foot|kitty)), no_blur on

# App window settings
windowrule = match:class ^(pomodorolm)$, float on
windowrule = match:class ^(pomodorolm)$, size 288 400
windowrule = match:class ^(pomodorolm)$, move 1587 268
windowrule = match:class ^(cameractrlsgtk)$, float on
