$terminal = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "foot" "kitty -1" "wezterm" "konsole" "kgx" "uxterm" "xterm"
$fileManager = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "thunar" "dolphin" "nautilus" "nemo" "kitty -1 fish -c yazi"
$browser = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "firefox" "zen-browser" "brave" "chromium" "opera" "librewolf"
$codeEditor = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "code" "command -v nvim && kitty -1 nvim" "antigravity" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v micro && kitty -1 micro"
$officeSoftware = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "onlyoffice-desktopeditors" "libreoffice" "wps" 
$textEditor = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "gnome-text-editor" "foot nvim" "kate" "emacs"
$volumeMixer = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "pavucontrol-qt" "pavucontrol"
$settingsApp = XDG_CURRENT_DESKTOP=gnome ~/.config/hypr/hyprland/scripts/launch_first_available.sh "qs -p ~/.config/quickshell/$qsConfig/settings.qml" "systemsettings" "gnome-control-center" "better-control"
$taskManager = ~/.config/hypr/hyprland/scripts/launch_first_available.sh "gnome-system-monitor" "plasma-systemmonitor --page-name Processes" "command -v btop && kitty -1 fish -c btop"

# The folder within ~/.config/quickshell containing the config
$qsConfig = ii

# Leave blank like this to load default config. Set to anything to not.
$dontLoadDefaultExecs =
$dontLoadDefaultGeneral =
$dontLoadDefaultRules =
$dontLoadDefaultKeybinds =
